# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/frmfamiliaslist.ui'
#
# Created: Sat Feb  4 02:08:27 2012
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Familias_listado(object):
    def setupUi(self, Familias_listado):
        Familias_listado.setObjectName(_fromUtf8("Familias_listado"))
        Familias_listado.resize(939, 792)
        self.centralwidget = QtGui.QWidget(Familias_listado)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tableWidget = QtGui.QTableWidget(self.centralwidget)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 4, item)
        self.gridLayout.addWidget(self.tableWidget, 0, 0, 1, 1)
        Familias_listado.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(Familias_listado)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 939, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_administracion = QtGui.QMenu(self.menubar)
        self.menu_administracion.setObjectName(_fromUtf8("menu_administracion"))
        self.menu_Herramientas = QtGui.QMenu(self.menubar)
        self.menu_Herramientas.setObjectName(_fromUtf8("menu_Herramientas"))
        self.menu_Ayuda = QtGui.QMenu(self.menubar)
        self.menu_Ayuda.setObjectName(_fromUtf8("menu_Ayuda"))
        self.menu_Familias = QtGui.QMenu(self.menubar)
        self.menu_Familias.setObjectName(_fromUtf8("menu_Familias"))
        self.menu_Archivo = QtGui.QMenu(self.menubar)
        self.menu_Archivo.setObjectName(_fromUtf8("menu_Archivo"))
        Familias_listado.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(Familias_listado)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        Familias_listado.setStatusBar(self.statusbar)
        self.action_Nuevo = QtGui.QAction(Familias_listado)
        self.action_Nuevo.setObjectName(_fromUtf8("action_Nuevo"))
        self.actionA_brir = QtGui.QAction(Familias_listado)
        self.actionA_brir.setObjectName(_fromUtf8("actionA_brir"))
        self.action_Guardar = QtGui.QAction(Familias_listado)
        self.action_Guardar.setObjectName(_fromUtf8("action_Guardar"))
        self.action_Salir = QtGui.QAction(Familias_listado)
        self.action_Salir.setObjectName(_fromUtf8("action_Salir"))
        self.actionAcerca_de_Komunal = QtGui.QAction(Familias_listado)
        self.actionAcerca_de_Komunal.setObjectName(_fromUtf8("actionAcerca_de_Komunal"))
        self.actionListado = QtGui.QAction(Familias_listado)
        self.actionListado.setObjectName(_fromUtf8("actionListado"))
        self.actionIngresar_Nucleo_Familiar = QtGui.QAction(Familias_listado)
        self.actionIngresar_Nucleo_Familiar.setObjectName(_fromUtf8("actionIngresar_Nucleo_Familiar"))
        self.actionAgregar_Concejo_Comunal = QtGui.QAction(Familias_listado)
        self.actionAgregar_Concejo_Comunal.setObjectName(_fromUtf8("actionAgregar_Concejo_Comunal"))
        self.actionGestionar_Consejos_Comunales = QtGui.QAction(Familias_listado)
        self.actionGestionar_Consejos_Comunales.setObjectName(_fromUtf8("actionGestionar_Consejos_Comunales"))
        self.actionManual_Komunal = QtGui.QAction(Familias_listado)
        self.actionManual_Komunal.setObjectName(_fromUtf8("actionManual_Komunal"))
        self.actionIndicadores = QtGui.QAction(Familias_listado)
        self.actionIndicadores.setObjectName(_fromUtf8("actionIndicadores"))
        self.actionExportar_Base_de_Datos = QtGui.QAction(Familias_listado)
        self.actionExportar_Base_de_Datos.setObjectName(_fromUtf8("actionExportar_Base_de_Datos"))
        self.actionSalir = QtGui.QAction(Familias_listado)
        self.actionSalir.setObjectName(_fromUtf8("actionSalir"))
        self.menu_administracion.addSeparator()
        self.menu_administracion.addAction(self.actionAgregar_Concejo_Comunal)
        self.menu_administracion.addAction(self.actionGestionar_Consejos_Comunales)
        self.menu_administracion.addAction(self.actionIndicadores)
        self.menu_Ayuda.addAction(self.actionAcerca_de_Komunal)
        self.menu_Ayuda.addAction(self.actionManual_Komunal)
        self.menu_Familias.addAction(self.actionListado)
        self.menu_Familias.addAction(self.actionIngresar_Nucleo_Familiar)
        self.menu_Archivo.addAction(self.actionExportar_Base_de_Datos)
        self.menu_Archivo.addSeparator()
        self.menu_Archivo.addAction(self.actionSalir)
        self.menubar.addAction(self.menu_Archivo.menuAction())
        self.menubar.addAction(self.menu_administracion.menuAction())
        self.menubar.addAction(self.menu_Familias.menuAction())
        self.menubar.addAction(self.menu_Herramientas.menuAction())
        self.menubar.addAction(self.menu_Ayuda.menuAction())

        self.retranslateUi(Familias_listado)
        QtCore.QObject.connect(self.actionSalir, QtCore.SIGNAL(_fromUtf8("activated()")), Familias_listado.close)
        QtCore.QObject.connect(self.actionListado, QtCore.SIGNAL(_fromUtf8("activated()")), self.centralwidget.hide)
        QtCore.QObject.connect(self.actionIngresar_Nucleo_Familiar, QtCore.SIGNAL(_fromUtf8("activated()")), self.centralwidget.show)
        QtCore.QMetaObject.connectSlotsByName(Familias_listado)

    def retranslateUi(self, Familias_listado):
        Familias_listado.setWindowTitle(QtGui.QApplication.translate("Familias_listado", "Censo Socio-Económico", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.verticalHeaderItem(0).setText(QtGui.QApplication.translate("Familias_listado", "header", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("Familias_listado", "Cedula", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("Familias_listado", "Nombre", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("Familias_listado", "Apellido", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("Familias_listado", "Sexo", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("Familias_listado", "Edad", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.item(0, 0).setText(QtGui.QApplication.translate("Familias_listado", "Cedula", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.item(0, 1).setText(QtGui.QApplication.translate("Familias_listado", "Nombre", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.item(0, 2).setText(QtGui.QApplication.translate("Familias_listado", "Apellido", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.item(0, 3).setText(QtGui.QApplication.translate("Familias_listado", "Sexo", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.item(0, 4).setText(QtGui.QApplication.translate("Familias_listado", "Edad", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.menu_administracion.setTitle(QtGui.QApplication.translate("Familias_listado", "&Administración", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Herramientas.setTitle(QtGui.QApplication.translate("Familias_listado", "&Herramientas", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Ayuda.setTitle(QtGui.QApplication.translate("Familias_listado", "&Ayuda", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Familias.setTitle(QtGui.QApplication.translate("Familias_listado", "&Familias", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Archivo.setTitle(QtGui.QApplication.translate("Familias_listado", "&Archivo", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Nuevo.setText(QtGui.QApplication.translate("Familias_listado", "&Nuevo", None, QtGui.QApplication.UnicodeUTF8))
        self.actionA_brir.setText(QtGui.QApplication.translate("Familias_listado", "A&brir", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Guardar.setText(QtGui.QApplication.translate("Familias_listado", "&Guardar", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Salir.setText(QtGui.QApplication.translate("Familias_listado", "&Salir", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Salir.setToolTip(QtGui.QApplication.translate("Familias_listado", "Salir de Komunal", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAcerca_de_Komunal.setText(QtGui.QApplication.translate("Familias_listado", "Acerca de Komunal", None, QtGui.QApplication.UnicodeUTF8))
        self.actionListado.setText(QtGui.QApplication.translate("Familias_listado", "Gestión Familias", None, QtGui.QApplication.UnicodeUTF8))
        self.actionIngresar_Nucleo_Familiar.setText(QtGui.QApplication.translate("Familias_listado", "Ingresar Nucleo Familiar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAgregar_Concejo_Comunal.setText(QtGui.QApplication.translate("Familias_listado", "Agregar Concejo Comunal", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGestionar_Consejos_Comunales.setText(QtGui.QApplication.translate("Familias_listado", "Gestionar Consejos Comunales", None, QtGui.QApplication.UnicodeUTF8))
        self.actionManual_Komunal.setText(QtGui.QApplication.translate("Familias_listado", "Manual Komunal", None, QtGui.QApplication.UnicodeUTF8))
        self.actionIndicadores.setText(QtGui.QApplication.translate("Familias_listado", "Indicadores", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExportar_Base_de_Datos.setText(QtGui.QApplication.translate("Familias_listado", "Exportar Base de Datos", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSalir.setText(QtGui.QApplication.translate("Familias_listado", "Salir", None, QtGui.QApplication.UnicodeUTF8))

